/**
 * appScaffold.ts — synthesizes a complete, runnable web-application project
 * from the AI Builder's UI specification plus the canvas pipeline context.
 *
 * The output mirrors what a coding agent would emit: a Next.js prediction
 * front-end wired to a FastAPI inference backend that serves the trained
 * model artifact. Everything is generated client-side from structured data,
 * so every chat refinement instantly rewrites the project tree.
 */

export interface UiSpecLike {
  brand: string;
  nav: string[];
  eyebrow: string;
  title: string;
  description: string;
  submitLabel: string;
  accent: "sky" | "violet" | "emerald";
  fields: Array<{ key: string; label: string; type: "number" | "text" | "select"; placeholder?: string; options?: string[] }>;
  stats?: Array<{ label: string; value: string; detail?: string }>;
  insight?: { title: string; description: string };
}

export interface ScaffoldFile {
  path: string;
  language: "tsx" | "ts" | "py" | "json" | "md" | "text";
  content: string;
}

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "neuralforge-app";
}

const ACCENT_HEX: Record<UiSpecLike["accent"], string> = {
  sky: "#0284c7",
  violet: "#7c3aed",
  emerald: "#059669",
};

export function generateAppFiles(
  spec: UiSpecLike,
  model: { name: string; format: string },
  options?: { trainingCode?: string },
): ScaffoldFile[] {
  const specJson = JSON.stringify(
    {
      ...spec,
      accentHex: ACCENT_HEX[spec.accent] ?? ACCENT_HEX.sky,
    },
    null,
    2,
  );
  const pkgName = slug(spec.brand);
  const trainingCode = options?.trainingCode?.trim()
    ? options.trainingCode
    : "# Export the training script from the NeuralForge canvas and paste it here.";

  const files: ScaffoldFile[] = [
    {
      path: "README.md",
      language: "md",
      content: [
        `# ${spec.brand}`,
        "",
        spec.description,
        "",
        `Model: **${model.name}** (${model.format.toUpperCase()} artifact)`,
        "",
        "## Structure",
        "",
        "```",
        "app/                 Next.js pages & API proxy",
        "components/          Prediction form UI",
        "backend/             FastAPI inference service",
        "```",
        "",
        "## Run locally",
        "",
        "```bash",
        "# 1. Train & export the model artifact (see backend/train.py)",
        "cd backend && pip install -r requirements.txt && python main.py",
        "",
        "# 2. Frontend",
        "npm install && npm run dev",
        "```",
        "",
        "## Environment",
        "",
        "Copy `.env.example` to `.env.local` and point `BACKEND_URL` at the running FastAPI service.",
      ].join("\n"),
    },
    {
      path: "package.json",
      language: "json",
      content: JSON.stringify(
        {
          name: pkgName,
          private: true,
          scripts: { dev: "next dev", build: "next build", start: "next start" },
          dependencies: { next: "^15.0.0", react: "^19.0.0", "react-dom": "^19.0.0" },
          devDependencies: { typescript: "^5.6.0", "@types/react": "^19.0.0", "@types/node": "^22.0.0" },
        },
        null,
        2,
      ),
    },
    {
      path: ".env.example",
      language: "text",
      content: "BACKEND_URL=http://localhost:8000\n",
    },
    {
      path: "app/layout.tsx",
      language: "tsx",
      content: [
        'import type { ReactNode } from "react";',
        `import "./globals.css";`,
        "",
        `export const metadata = { title: "${spec.brand}", description: ${JSON.stringify(spec.description)} };`,
        "",
        'const NAV = ' + JSON.stringify(spec.nav) + ';',
        "",
        "export default function RootLayout({ children }: { children: ReactNode }) {",
        "  return (",
        '    <html lang="en">',
        "      <body>",
        "        <header className=\"site-header\">",
        "          <span className=\"brand\">" + spec.brand + "</span>",
        "          <nav>",
        "            {NAV.map((item) => (<a key={item} href=\"#\">{item}</a>))}",
        "          </nav>",
        "        </header>",
        "        {children}",
        "      </body>",
        "    </html>",
        "  );",
        "}",
      ].join("\n"),
    },
    {
      path: "app/page.tsx",
      language: "tsx",
      content: [
        'import PredictionForm from "@/components/PredictionForm";',
        "",
        "const SPEC = " + specJson + ";",
        "",
        "export default function Home() {",
        "  return (",
        "    <main className=\"page\">",
        "      <section className=\"hero\">",
        "        <p className=\"eyebrow\">{SPEC.eyebrow}</p>",
        "        <h1>{SPEC.title}</h1>",
        "        <p className=\"lead\">{SPEC.description}</p>",
        "        {(SPEC.stats ?? []).map((stat) => (",
        "          <div key={stat.label} className=\"stat\">",
        "            <span className=\"stat-label\">{stat.label}</span>",
        "            <strong>{stat.value}</strong>",
        "          </div>",
        "        ))}",
        "      </section>",
        "      <PredictionForm fields={SPEC.fields} submitLabel={SPEC.submitLabel} accent={SPEC.accentHex} />",
        "      {SPEC.insight ? (",
        "        <section className=\"insight\">",
        "          <h2>{SPEC.insight.title}</h2>",
        "          <p>{SPEC.insight.description}</p>",
        "        </section>",
        "      ) : null}",
        "    </main>",
        "  );",
        "}",
      ].join("\n"),
    },
    {
      path: "app/globals.css",
      language: "text",
      content: [
        ":root { font-family: system-ui, sans-serif; }",
        ".site-header { display:flex; justify-content:space-between; padding:16px 24px; border-bottom:1px solid #e5e7eb; }",
        ".brand { font-weight:700; }",
        "nav a { margin-left:20px; color:#475569; text-decoration:none; font-size:14px; }",
        ".page { max-width:880px; margin:0 auto; padding:48px 24px; }",
        ".eyebrow { letter-spacing:.18em; font-size:12px; font-weight:700; color:var(--accent); }",
        ".stat-label { display:block; font-size:11px; color:#64748b; text-transform:uppercase; }",
        ".insight { margin-top:40px; padding:20px; border-radius:12px; background:#f8fafc; border:1px solid #e5e7eb; }",
        "form .field { margin-bottom:14px; }",
        "form label { display:block; font-size:13px; font-weight:600; margin-bottom:4px; }",
        "form input, form select { width:100%; padding:10px; border:1px solid #cbd5e1; border-radius:8px; font-size:14px; }",
        "button.submit { width:100%; padding:12px; border:0; border-radius:8px; background:var(--accent); color:#fff; font-weight:600; cursor:pointer; }",
        ".error-text { color:#dc2626; font-size:12px; margin-top:4px; }",
        ".result-card { margin-top:16px; padding:14px; border-radius:8px; background:#ecfdf5; border:1px solid #a7f3d0; font-size:14px; }",
      ].join("\n"),
    },
    {
      path: "components/PredictionForm.tsx",
      language: "tsx",
      content: [
        '"use client";',
        "",
        'import { useState } from "react";',
        "",
        "type Field = { key: string; label: string; type: \"number\" | \"text\" | \"select\"; placeholder?: string; options?: string[] };",
        "",
        "interface Props {",
        "  fields: Field[];",
        "  submitLabel: string;",
        "  accent: string;",
        "}",
        "",
        "export default function PredictionForm({ fields, submitLabel, accent }: Props) {",
        "  const [values, setValues] = useState<Record<string, string>>({});",
        "  const [errors, setErrors] = useState<Record<string, string>>({});",
        "  const [result, setResult] = useState<{ prediction?: unknown; probabilities?: Record<string, number>; error?: string } | null>(null);",
        "  const [busy, setBusy] = useState(false);",
        "",
        "  const validate = () => {",
        "    const next: Record<string, string> = {};",
        "    for (const field of fields) {",
        "      const raw = (values[field.key] ?? \"\").trim();",
        '      if (!raw) next[field.key] = "Required";',
        '      else if (field.type === "number" && Number.isNaN(Number(raw))) next[field.key] = "Must be a number";',
        "    }",
        "    setErrors(next);",
        "    return Object.keys(next).length === 0;",
        "  };",
        "",
        "  const submit = async () => {",
        "    if (!validate()) return;",
        "    setBusy(true); setResult(null);",
        "    try {",
        "      const payload = Object.fromEntries(fields.map((f) => [f.key, f.type === \"number\" ? Number(values[f.key]) : values[f.key]]));",
        "      const res = await fetch(\"/api/predict\", { method: \"POST\", headers: { \"Content-Type\": \"application/json\" }, body: JSON.stringify(payload) });",
        "      setResult(await res.json());",
        "    } catch {",
        '      setResult({ error: "Could not reach the inference backend." });',
        "    } finally {",
        "      setBusy(false);",
        "    }",
        "  };",
        "",
        "  return (",
        "    <form style={{ \"--accent\": accent } as React.CSSProperties} onSubmit={(e) => { e.preventDefault(); void submit(); }}>",
        "      {fields.map((field) => (",
        "        <div className=\"field\" key={field.key}>",
        "          <label htmlFor={field.key}>{field.label}</label>",
        '          {field.type === "select" ? (',
        "            <select id={field.key} value={values[field.key] ?? \"\"} onChange={(e) => setValues((v) => ({ ...v, [field.key]: e.target.value }))}>",
        '              <option value="" disabled>Select…</option>',
        "              {(field.options ?? []).map((o) => (<option key={o} value={o}>{o}</option>))}",
        "            </select>",
        "          ) : (",
        "            <input id={field.key} type={field.type} placeholder={field.placeholder ?? \"\"} value={values[field.key] ?? \"\"}",
        "              onChange={(e) => setValues((v) => ({ ...v, [field.key]: e.target.value }))} />",
        "          )}",
        "          {errors[field.key] ? <span className=\"error-text\">{errors[field.key]}</span> : null}",
        "        </div>",
        "      ))}",
        "      <button className=\"submit\" type=\"submit\" disabled={busy}>{busy ? \"Predicting…\" : submitLabel}</button>",
        "      {result?.error ? <div className=\"result-card\" style={{ background: \"#fef2f2\", borderColor: \"#fecaca\" }}>{result.error}</div> : null}",
        "      {result?.prediction !== undefined ? (",
        '          <div className="result-card">Prediction: <strong>{String(result.prediction)}</strong>',
        "          {result.probabilities ? (<ul>{Object.entries(result.probabilities).map(([cls, p]) => (<li key={cls}>{cls}: {(p * 100).toFixed(1)}%</li>))}</ul>) : null}",
        "        </div>",
        "      ) : null}",
        "    </form>",
        "  );",
        "}",
      ].join("\n"),
    },
    {
      path: "app/api/predict/route.ts",
      language: "ts",
      content: [
        'import { NextResponse, type NextRequest } from "next/server";',
        "",
        "/** Thin proxy so browser calls never hit the Python service directly. */",
        "export async function POST(req: NextRequest) {",
        "  const base = process.env.BACKEND_URL ?? \"http://localhost:8000\";",
        "  try {",
        '    const upstream = await fetch(`${base}/predict`, {',
        '      method: "POST",',
        '      headers: { "Content-Type": "application/json" },',
        "      body: JSON.stringify(await req.json()),",
        "    });",
        '    return NextResponse.json(await upstream.json(), { status: upstream.status });',
        "  } catch {",
        '    return NextResponse.json({ error: "Inference backend unreachable" }, { status: 502 });',
        "  }",
        "}",
      ].join("\n"),
    },
    {
      path: "backend/main.py",
      language: "py",
      content: [
        '"""FastAPI inference service for the ' + spec.brand + ' prediction app."""',
        "import json",
        "from pathlib import Path",
        "",
        "import joblib",
        "import pandas as pd",
        "from fastapi import FastAPI, HTTPException",
        "from fastapi.middleware.cors import CORSMiddleware",
        "from pydantic import BaseModel, RootModel",
        "",
        'MODEL_PATH = Path(__file__).parent / "model.joblib"',
        'SCHEMA_PATH = Path(__file__).parent / "schema.json"',
        "",
        "app = FastAPI(title=" + JSON.stringify(spec.brand) + ")",
        'app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])',
        "",
        "pipeline = joblib.load(MODEL_PATH) if MODEL_PATH.exists() else None",
        'SCHEMA = json.loads(SCHEMA_PATH.read_text()) if SCHEMA_PATH.exists() else {"feature_columns": []}',
        "",
        "class PredictRequest(RootModel[dict[str, float | str | int]]):",
        "    pass",
        "",
        '@app.get("/health")',
        "def health():",
        '    return {"ok": pipeline is not None, "features": SCHEMA["feature_columns"]}',
        "",
        '@app.post("/predict")',
        "def predict(body: PredictRequest):",
        "    if pipeline is None:",
        '        raise HTTPException(503, "Model not trained yet — run train.py first.")',
        "    row = {}",
        '    missing = [c for c in SCHEMA["feature_columns"] if c not in body.root]',
        "    if missing:",
        '        raise HTTPException(400, f"missing features: {missing}")',
        '    for column in SCHEMA["feature_columns"]:',
        "        row[column] = body.root[column]",
        "    frame = pd.DataFrame([row]).reindex(columns=pipeline.feature_names_in_, fill_value=0)",
        '    result = {"prediction": str(pipeline.predict(frame)[0]), "target": SCHEMA.get("target")}',
        "    try:",
        "        proba = pipeline.predict_proba(frame)[0]",
        '        result["probabilities"] = {str(c): round(float(p), 4) for c, p in zip(pipeline.classes_, proba)}',
        "    except Exception:",
        "        pass",
        "    return result",
      ].join("\n"),
    },
    {
      path: "backend/requirements.txt",
      language: "text",
      content: ["fastapi>=0.110", "uvicorn[standard]>=0.29", "scikit-learn>=1.4", "pandas>=2.2", "joblib>=1.3"].join("\n"),
    },
    {
      path: "backend/train.py",
      language: "py",
      content: [
        '"""Trains the canvas pipeline and writes model.joblib + schema.json."""',
        "import json",
        "from pathlib import Path",
        "",
        "import joblib",
        "from sklearn.pipeline import Pipeline",
        "",
        trainingCode,
        "",
        '# Persist artifacts for main.py (expects fitted `pipeline`, features X):',
        'feature_names = getattr(X, "columns", None)',
        'feature_list = list(map(str, feature_names)) if feature_names is not None else [f"f{i}" for i in range(X.shape[1])]',
        'Path("model.joblib").write_bytes(b"")  # replaced below',
        'joblib.dump(pipeline, Path("model.joblib"))',
        'Path("schema.json").write_text(json.dumps({"feature_columns": feature_list, "target": "target"}))',
        'print("Saved model.joblib and schema.json — restart main.py to serve.")',
      ].join("\n"),
    },
  ];

  return files;
}
