/**
 * Shared domain types for the Hybrid ML Canvas platform.
 */

export type NodeCategory =
  | "data"
  | "preprocessing"
  | "classic_ml"
  | "deep_learning"
  | "visualization";

export type ExecutionRoute = "instant" | "colab";

/** Chart families the visualization nodes draw their checkbox lists from. */
export type ChartGroup = "core" | "scatter" | "knn" | "diagnostics";

/**
 * Every figure the instant engine can produce. Nothing is rendered unless the
 * user ticks it on a Visualization node — the engine only computes what was
 * asked for.
 */
export type ChartKey =
  // core evaluation
  | "confusion_matrix"
  | "roc_curve"
  | "pr_curve"
  | "feature_importance"
  | "per_class_metrics"
  | "threshold_curve"
  // scatter / geometry
  | "scatter_2d"
  | "scatter_3d"
  | "splom"
  | "decision_boundary"
  | "embedding"
  | "confidence_scatter"
  // k-nearest-neighbour analysis
  | "knn_k_sweep"
  | "knn_boundary"
  | "knn_neighbor_graph"
  | "knn_distance_hist"
  | "knn_vote_scatter"
  // diagnostics
  | "learning_curve"
  | "cv_scores"
  | "calibration"
  | "class_balance"
  | "correlation";

/** A draggable node palette definition. */
export interface PaletteItem {
  type: string;
  label: string;
  description: string;
  category: NodeCategory;
  /** Icon registry name, resolved at runtime by lib/icons. */
  icon: string;
  accent: string;
  params?: NodeParam[];
}

/** How the Inspector renders a parameter control. */
export type ParamKind = "number" | "text" | "select" | "slider" | "toggle" | "charts";

export interface NodeParam {
  key: string;
  label: string;
  value: string | number;
  options?: string[];
  hint?: string;
  /** Defaults to "select" when `options` is present, else number/text by value type. */
  kind?: ParamKind;
  /** Slider bounds (kind === "slider"). */
  min?: number;
  max?: number;
  step?: number;
  /** For kind === "charts": which catalog group the checkbox list is drawn from. */
  chartGroup?: ChartGroup;
}

/** A user-imported CSV dataset attached to a custom data node. */
export interface CsvDataset {
  filename: string;
  targetColumn: string;
  columns: string[];
  nrows: number;
  csvText: string;
}

/** SQL dialect behind a Cloud Database source node. */
export type DbDialect = "postgres" | "mysql";

/** Connection + query state persisted on a Cloud Database (data:db) node. */
export interface DbSourceConfig {
  connectionString: string;
  query: string;
  dialect: DbDialect;
  /** idle = not configured yet, connected = last fetch succeeded, error = last fetch failed. */
  status: "idle" | "connected" | "error";
  /** Friendly message from the last failed fetch. */
  error?: string;
  fetchedAt?: string;
  rowCount?: number;
  queryMs?: number;
}

/** Per-column decision for repairing text columns that feed a numeric pipeline. */
export type TextColumnResolution = "drop" | "label" | "onehot";

/** A user-imported image dataset (grayscale-encoded samples) for classification. */
export interface ImageDataset {
  name: string;
  classNames: string[];
  /** class index per sample */
  labels: number[];
  /** flattened grayscale pixel vector per sample (length = width * height) */
  vectors: number[][];
  width: number;
  height: number;
  nsamples: number;
  /** small data-URL previews (capped) */
  thumbnails: string[];
}

/** Data carried by a React Flow node. */
export interface MLNodeData {
  type: string;
  label: string;
  description: string;
  category: NodeCategory;
  icon: string;
  accent: string;
  params?: NodeParam[];
  /** Present on custom CSV data nodes — the user's imported dataset. */
  dataset?: CsvDataset;
  /** Present on custom image data nodes — grayscale-encoded samples. */
  imageDataset?: ImageDataset;
  /** Present on Cloud Database (data:db) nodes — connection + query state. */
  dbConfig?: DbSourceConfig;
  /** Lifecycle marker stamped by the canvas during a training run. */
  executionStatus?: "running" | "success" | "error";
  /** selection ring / active state */
  selected?: boolean;
  [key: string]: unknown;
}

/** A generic Plotly figure payload (the `fig.to_dict()` shape). */
export interface PlotlyFigure {
  data: unknown[];
  layout: Record<string, unknown>;
}

export interface PipelineStep {
  name: string;
  detail: string;
  kind: string;
}

export interface DatasetInfo {
  name: string;
  n_samples: number;
  n_features: number;
  n_classes: number;
  target_type: string;
}

export interface ModelArtifact {
  format: "pickle" | "joblib" | "onnx" | "torchscript" | "pytorch";
  filename: string;
  mime: string;
  /** Base64 payload for artifacts generated by the local training engine. */
  base64?: string;
  /** Human-readable note when the artifact must be created in Colab. */
  instructions?: string;
}

export interface ModelInfo {
  name: string;
  framework: string;
  library_version?: string;
  params?: Record<string, unknown>;
  export_formats?: Array<ModelArtifact["format"]>;
}

export interface MetricSet {
  accuracy: number;
  precision: number;
  recall: number;
  f1: number;
  roc_auc: number;
  average_precision: number;
  log_loss?: number;
  balanced_accuracy?: number;
  mcc?: number;
}

export interface TimingInfo {
  total_seconds: number;
  training_seconds: number;
  charts_seconds?: number;
}

/** Raw test-set predictions for the results table + CSV export. */
export interface PredictionSet {
  y_true: number[];
  y_pred: number[];
  classes: string[];
  n_test: number;
  /** Model confidence (max predicted probability) per row, when available. */
  confidence?: number[];
}

/** Per-class precision / recall / F1 breakdown. */
export interface PerClassMetric {
  label: string;
  precision: number;
  recall: number;
  f1: number;
  support: number;
}

/** Only the figures the user requested are present. */
export type ChartBundle = Partial<Record<ChartKey, PlotlyFigure>>;

/** A chart that was requested but could not be produced, and why. */
export interface SkippedChart {
  key: string;
  reason: string;
}

/** Response shape when the graph contains only basic ML nodes. */
export interface InstantExecutionResponse {
  route: Extract<ExecutionRoute, "instant">;
  status: "success" | "error";
  engine: string;
  pipeline: { steps: PipelineStep[] };
  dataset: DatasetInfo;
  model: ModelInfo;
  metrics: MetricSet;
  charts: ChartBundle;
  /** Keys the user asked for (in catalog order). */
  charts_requested?: string[];
  /** Requested-but-unavailable charts with a human-readable reason. */
  charts_skipped?: SkippedChart[];
  per_class?: PerClassMetric[];
  predictions: PredictionSet;
  timing: TimingInfo;
  message?: string;
  error?: string;
}

/** Response shape when advanced AI / deep-learning nodes are present. */
export interface ColabExecutionResponse {
  route: Extract<ExecutionRoute, "colab">;
  status: "success" | "error";
  engine: string;
  notebook: {
    filename: string;
    nbformat: number;
    cells: number;
    size_bytes: number;
    title: string;
  };
  /** Full .ipynb content serialized as JSON string. */
  notebook_json: string;
  colab_url: string;
  download_url: string;
  requirements: string[];
  recommended_runtime: string;
  nodes_detected: string[];
  message?: string;
  error?: string;
}

export type ExecutionResponse = InstantExecutionResponse | ColabExecutionResponse;

/** The compact graph payload sent to the backend. */
export interface GraphNodePayload {
  id: string;
  type: string;
  category: NodeCategory;
  label: string;
  params?: Record<string, string | number>;
  dataset?: CsvDataset;
  imageDataset?: ImageDataset;
  position: { x: number; y: number };
}

export interface GraphEdgePayload {
  id: string;
  source: string;
  target: string;
}

export interface GraphPayload {
  nodes: GraphNodePayload[];
  edges: GraphEdgePayload[];
  meta?: {
    title?: string;
    created_at?: string;
  };
}
