"use client";
import { useMemo, useState } from "react";
import { Check, ClipboardText, Code, DownloadSimple, GearSix, MagicWand, Plus, Sparkle, Trash } from "@phosphor-icons/react";

type Stop={id:number;color:string;position:number};
type Kind="linear"|"radial";
const presets=[['Solar flare','#FF7A00','#FFB347',135],['Electric violet','#5B21B6','#C026D3',135],['Ocean breeze','#0EA5E9','#14B8A6',120],['Berry blast','#DB2777','#7C3AED',150],['Mint dusk','#34D399','#0F766E',145],['Neon sky','#2563EB','#A855F7',125]] as const;
const makeGradient=(kind:Kind,angle:number,stops:Stop[])=>{const colors=[...stops].sort((a,b)=>a.position-b.position).map(s=>`${s.color} ${s.position}%`).join(', ');return kind==='linear'?`linear-gradient(${angle}deg, ${colors})`:`radial-gradient(circle, ${colors})`};

export function GradientStudio(){
 const [kind,setKind]=useState<Kind>('linear'); const [angle,setAngle]=useState(135); const [stops,setStops]=useState<Stop[]>([{id:1,color:'#FF8A00',position:0},{id:2,color:'#FFB347',position:100}]); const [copied,setCopied]=useState(false); const [id,setId]=useState(3);
 const value=useMemo(()=>makeGradient(kind,angle,stops),[kind,angle,stops]); const css=`.gradient-background {\n  background: ${value};\n}`;
 const update=(id:number,patch:Partial<Stop>)=>setStops(s=>s.map(x=>x.id===id?{...x,...patch}:x));
 const add=()=>{if(stops.length<5){setStops(s=>[...s,{id,color:'#F97316',position:50}]);setId(x=>x+1)}};
 const copy=async()=>{await navigator.clipboard.writeText(css);setCopied(true);setTimeout(()=>setCopied(false),1600)};
 const download=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([css],{type:'text/css'}));a.download='gradient.css';a.click()};
 const preset=(p:typeof presets[number])=>{setKind('linear');setAngle(p[3]);setStops([{id:1,color:p[1],position:0},{id:2,color:p[2],position:100}])};
 return <main className="min-h-screen bg-[#f7f8fa] text-[#20232a]">
  <header className="flex h-20 items-center justify-between border-b border-[#e2e5e9] bg-white px-6 lg:px-10"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#ff8a00] text-white"><Sparkle size={19} weight="fill"/></span><div><b className="block text-[15px]">Gradient Studio</b><small className="text-[10px] uppercase tracking-[.16em] text-[#9aa0a8]">Visual CSS generator</small></div></div><div className="flex gap-2"><button onClick={download} className="hidden h-9 items-center gap-2 rounded-lg border border-[#e2e5e9] px-3 text-xs font-semibold sm:flex"><DownloadSimple size={15}/>Export CSS</button><button aria-label="Settings" className="flex h-9 w-9 items-center justify-center rounded-lg border border-[#e2e5e9]"><GearSix size={17}/></button></div></header>
  <div className="mx-auto grid max-w-[1440px] gap-6 px-5 py-6 lg:grid-cols-[230px_minmax(0,1fr)_290px] lg:px-8">
   <aside className="rounded-xl border border-[#e2e5e9] bg-white p-4"><div className="mb-5 flex justify-between"><h2 className="text-[11px] uppercase tracking-[.16em] text-[#737983]">Presets</h2><MagicWand size={16} className="text-[#ff8a00]"/></div><div className="grid grid-cols-2 gap-2 lg:grid-cols-1">{presets.map(p=><button key={p[0]} onClick={()=>preset(p)} className="flex items-center gap-3 rounded-lg p-2 text-left hover:bg-[#f5f6f8]"><span className="h-9 w-9 shrink-0 rounded-md" style={{background:`linear-gradient(135deg,${p[1]},${p[2]})`}}/><span className="truncate text-xs font-semibold text-[#5f6670]">{p[0]}</span></button>)}</div></aside>
   <section className="min-w-0"><div className="mb-4 flex items-end justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#ff8a00]">Untitled gradient</p><h1 className="mt-1 text-xl font-bold">Build your background</h1></div><span className="rounded-full bg-[#fff1e3] px-3 py-1 text-[10px] font-bold uppercase text-[#e87900]">Live preview</span></div><div className="relative flex min-h-[450px] items-center justify-center overflow-hidden rounded-xl border border-[#e2e5e9] bg-white p-5"><div className="absolute inset-0 opacity-30" style={{backgroundImage:'linear-gradient(#e6e8eb 1px,transparent 1px),linear-gradient(90deg,#e6e8eb 1px,transparent 1px)',backgroundSize:'28px 28px'}}/><div className="relative flex aspect-[1.6] w-full max-w-[680px] items-center justify-center rounded-xl shadow-2xl" style={{background:value}}><span className="rounded-lg bg-black/10 px-4 py-2 text-[11px] font-semibold text-white backdrop-blur">Your gradient preview</span></div></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#e2e5e9] bg-white px-4 py-3"><div className="flex items-center gap-3"><span className="text-xs font-semibold text-[#666c75]">Type</span><div className="rounded-lg bg-[#f1f2f4] p-1">{(['linear','radial'] as Kind[]).map(k=><button key={k} onClick={()=>setKind(k)} className={`rounded-md px-3 py-1.5 text-[11px] font-bold capitalize ${kind===k?'bg-white shadow-sm':'text-[#8b9098]'}`}>{k}</button>)}</div></div><label className="flex items-center gap-2 text-xs text-[#777d86]">Angle <input aria-label="Gradient angle" type="range" min="0" max="360" value={angle} onChange={e=>setAngle(+e.target.value)} className="accent-[#ff8a00]"/><b className="w-8 text-right text-[#20232a]">{angle}°</b></label></div></section>
   <aside className="rounded-xl border border-[#e2e5e9] bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-bold">Gradient stops</h2><button onClick={add} aria-label="Add color stop" className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#fff1e3] text-[#ed7900]"><Plus size={16}/></button></div><div className="mt-6 h-5 rounded-md" style={{background:value}}/><div className="mt-5 space-y-4">{stops.sort((a,b)=>a.position-b.position).map(s=><div key={s.id} className="flex items-center gap-2"><input aria-label={`Color stop ${s.id}`} type="color" value={s.color} onChange={e=>update(s.id,{color:e.target.value})} className="h-9 w-9 cursor-pointer rounded-md border-0 bg-transparent p-0"/><input value={s.color} onChange={e=>update(s.id,{color:e.target.value})} className="h-9 w-20 rounded-lg border border-[#e2e5e9] px-2 font-mono text-[11px] uppercase"/><input aria-label={`Position ${s.id}`} type="number" min="0" max="100" value={s.position} onChange={e=>update(s.id,{position:Math.max(0,Math.min(100,+e.target.value||0))})} className="h-9 w-14 rounded-lg border border-[#e2e5e9] px-2 text-xs"/><span className="text-[11px] text-[#9aa0a8]">%</span>{stops.length>2&&<button aria-label="Remove stop" onClick={()=>setStops(x=>x.filter(y=>y.id!==s.id))} className="ml-auto text-[#a4a9b0] hover:text-red-500"><Trash size={15}/></button>}</div>)}</div><div className="mt-7 border-t border-[#eceef0] pt-5"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-bold">CSS output</h2><Code size={16} className="text-[#ff8a00]"/></div><pre className="overflow-auto rounded-lg bg-[#20232a] p-3 text-[10px] leading-5 text-[#d7dbe0]">{css}</pre><div className="mt-3 flex gap-2"><button onClick={copy} className="flex h-9 flex-1 items-center justify-center gap-2 rounded-lg bg-[#ff8a00] text-xs font-bold text-white">{copied?<Check size={15}/>:<ClipboardText size={15}/>} {copied?'Copied':'Copy CSS'}</button><button onClick={download} aria-label="Download stylesheet" className="flex h-9 w-10 items-center justify-center rounded-lg border border-[#e2e5e9]"><DownloadSimple size={16}/></button></div></div></aside>
  </div>
 </main>
}

export default GradientStudio;
